version: '3'
services:
  celery:
    build:
      context: .
      dockerfile: ./dev/celery.Dockerfile
    command: [
      "bash", "-c",
      "/usr/bin/shiny-server /etc/shiny-server/shiny-server.conf &
      celery --app optimal_transport_morphometry.celery worker --loglevel INFO --without-heartbeat"
    ]
    restart: unless-stopped
    # Docker Compose does not set the TTY width, which causes Celery errors
    tty: false
    env_file: .env
    volumes:
      - .:/opt/django-project
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
