version: '3'
services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "bash", "-c",
      "/usr/bin/shiny-server /etc/shiny-server/shiny-server.conf &
      celery --app optimal_transport_morphometry.celery worker --loglevel INFO --without-heartbeat"
    ]
    restart: unless-stopped
    # Docker Compose does not set the TTY width, which causes Celery errors
    tty: false
    env_file: .env
    volumes:
      - .:/opt/django-project
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672

  minio:
    # image: minio/minio:latest
    image: minio/minio:RELEASE.2022-01-28T02-28-16Z
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command:
      [
        "server",
        "/data",
        "--console-address",
        ":${DOCKER_MINIO_CONSOLE_PORT-9001}"
      ]
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
      - ${DOCKER_MINIO_CONSOLE_PORT-9001}:9001
