# Generated by Django 3.1.3 on 2020-11-14 01:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields

import optimal_transport_morphometry.core.models.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'blob',
                    s3_file_field.fields.S3FileField(
                        max_length=2000,
                        upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='', max_length=3000)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='upload_batches',
                        to='core.dataset',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pending_uploads',
                        to='core.uploadbatch',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pending_uploads',
                        to='core.patient',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        default=optimal_transport_morphometry.core.models.image.ImageType[
                            'structural_mri'
                        ],
                        max_length=100,
                    ),
                ),
                (
                    'blob',
                    s3_file_field.fields.S3FileField(
                        max_length=2000,
                        upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                    ),
                ),
                (
                    'metadata',
                    optimal_transport_morphometry.core.models.image.MetadataField(
                        blank=True, default=dict
                    ),
                ),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='core.dataset',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='core.patient',
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingupload',
            index=models.Index(fields=['batch', 'name'], name='core_pendin_batch_i_520706_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['dataset'], name='core_image_dataset_9750b7_idx'),
        ),
    ]
