# Generated by Django 3.1.3 on 2020-11-20 21:38

from django.db import migrations, models

import optimal_transport_morphometry.core.models.metadata


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_initial_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadbatch',
            options={'verbose_name': 'upload batch', 'verbose_name_plural': 'upload batches'},
        ),
        migrations.AddField(
            model_name='pendingupload',
            name='metadata',
            field=optimal_transport_morphometry.core.models.metadata.MetadataField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
