# Generated by Django 3.1.3 on 2020-11-23 16:06

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20201120_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddConstraint(
            model_name='pendingupload',
            constraint=models.UniqueConstraint(fields=('batch', 'name'), name='unique_name'),
        ),
    ]
