# Generated by Django 3.1.5 on 2021-01-23 16:15

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_segmentedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jacobianimage',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='registeredimage',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='segmentedimage',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='jacobianimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jacobianimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='registeredimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='segmentedimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentedimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
    ]
