# Generated by Django 3.1.5 on 2021-02-04 16:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210123_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jacobianimage',
            name='registration_type',
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'blob',
                    s3_file_field.fields.S3FileField(
                        max_length=2000,
                        upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                    ),
                ),
                ('downsample_factor', models.FloatField()),
                (
                    'atlas',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='feature_images',
                        to='core.atlas',
                    ),
                ),
                (
                    'source_image',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feature_images',
                        to='core.image',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
