# Generated by Django 3.2.4 on 2021-06-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20210204_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='preprocessing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
