# Generated by Django 3.2.13 on 2022-06-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20210629_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='datasets_owned',
                to='auth.user',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
