# Generated by Django 3.2.15 on 2022-08-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_image_unique_dataset_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jacobianimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registeredimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentedimage',
            options={},
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='atlas',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='core_featureimages',
                to='core.atlas',
            ),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='source_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_featureimages',
                to='core.image',
            ),
        ),
        migrations.AlterField(
            model_name='jacobianimage',
            name='atlas',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='core_jacobianimages',
                to='core.atlas',
            ),
        ),
        migrations.AlterField(
            model_name='jacobianimage',
            name='source_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_jacobianimages',
                to='core.image',
            ),
        ),
        migrations.AlterField(
            model_name='registeredimage',
            name='atlas',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='core_registeredimages',
                to='core.atlas',
            ),
        ),
        migrations.AlterField(
            model_name='registeredimage',
            name='source_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_registeredimages',
                to='core.image',
            ),
        ),
        migrations.AlterField(
            model_name='segmentedimage',
            name='atlas',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='core_segmentedimages',
                to='core.atlas',
            ),
        ),
        migrations.AlterField(
            model_name='segmentedimage',
            name='source_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='core_segmentedimages',
                to='core.image',
            ),
        ),
    ]
