# Generated by Django 3.2.15 on 2022-08-17 21:46
from pathlib import Path

from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import migrations

project_dir = Path(__file__).parent.parent.parent.parent
atlases_dir = project_dir / 'sample_data' / 'atlases'


def populate_compressed_atlases(apps, schema_editor):
    Atlas = apps.get_model('core', 'Atlas')
    for atlas_file in atlases_dir.glob('*.nii.gz'):
        with open(atlas_file, 'rb') as f:
            Atlas.objects.create(
                name=atlas_file.name,
                blob=SimpleUploadedFile(name=atlas_file.name, content=f.read()),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220816_2130'),
    ]

    operations = [
        migrations.RunPython(populate_compressed_atlases, migrations.RunPython.noop),
    ]
