# Generated by Django 3.2.15 on 2022-09-23 21:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220923_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='analysis_status',
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('zip_file', s3_file_field.fields.S3FileField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Pending', 'Pending'),
                            ('Running', 'Running'),
                            ('Finished', 'Finished'),
                            ('Failed', 'Failed'),
                        ],
                        default='Pending',
                        max_length=32,
                    ),
                ),
                ('error_message', models.TextField(blank=True, default='')),
                (
                    'preprocessing_batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='analysis_results',
                        to='core.preprocessingbatch',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_analysis_result',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.analysisresult',
            ),
        ),
    ]
